# Site settings
title: S tahoe
email: stahoe@productteams.com
description: > # this means to ignore newlines until "baseurl:"
  Digital Concierge for the South Tahoe area
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://stahoe.com" # the base hostname & protocol for your site
twitter_username: Stahoelife
github_username:  jekyll

# Build settings
markdown: kramdown
